// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieuabsssepfcfqoxlbop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldWFic3NzZXBmY2Zxb3hsYm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzk4NzcsImV4cCI6MjA2NTU1NTg3N30.jUSE9gixKIQvgAkKiBi4C4heGPsM5_APyHLQdAoL5Pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);